domain: "rudicito.github.io"
url: "https://rudicito.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "rudicito" # the name of your site, e.g. ACME Corp.
    
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - scripts/

language_default: en

collections_dir: content
collections:
  fr:
    output: true
    permalink: /fr/:slug
  fr_projects:
    output: true
    permalink: /fr/projects/:slug
  en:
    output: true
    permalink: /en/:slug
  en_projects:
    output: true
    permalink: /en/projects/:slug

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "fr"
    values:
      layout: "default"
      lang: "fr"
  - scope:
      path: ""
      type: "fr_projects"
    values:
      layout: "projects"
      lang: "fr"

  - scope:
      path: ""
      type: "en"
    values:
      layout: "default"
      lang: "en"
  - scope:
      path: ""
      type: "en_projects"
    values:
      layout: "projects"
      lang: "en"