domain: "rudicito.github.io"
url: "https://rudicito.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "rudicito" # the name of your site, e.g. ACME Corp.

collections:
  projects:
    output: true
    permalink: /projects/:path/